#!/usr/bin/env python3
# Copyright 2023 The XLS Authors

import pathlib

top_dir = pathlib.Path(__file__).parent

with open(top_dir / 'techmap.v', "w") as f:
    f.write("""\
/**
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 */

/** DO NOT EDIT -- This file is generated by `make_techmap_v.py` file **/

(* techmap_celltype = "$add" *)
module _map_add(A, B, Y);

    parameter A_SIGNED = 0;
    parameter B_SIGNED = 0;
    parameter A_WIDTH = 1;
    parameter B_WIDTH = 1;
    parameter Y_WIDTH = 1;

    (* force_downto *)
    input [A_WIDTH-1:0] A;
    (* force_downto *)
    input [B_WIDTH-1:0] B;
    (* force_downto *)
    output [Y_WIDTH-1:0] Y;

    // Simple sanity checks
    //wire _TECHMAP_FAIL_ = A_WIDTH != Y_WIDTH;
    //wire _TECHMAP_FAIL_ = B_WIDTH != Y_WIDTH;

    genvar i;
    generate
        if (A_WIDTH == 2)
            /* Map 2-bit wide adder */
            add_b02 _TECHMAP_REPLACE_ (.a(A), .b(B), .o(Y));""")
    for i in range(3, 64):
        f.write("""
        else if (A_WIDTH == {i})
            /* Map {i}-bit wide adder */
            add_b{i:02} _TECHMAP_REPLACE_ (.a(A), .b(B), .o(Y));""".format(i=i))
    f.write("""
    endgenerate
endmodule
""")
