#!/usr/bin/env python3
# Copyright 2023 The XLS Authors

import pathlib

top_dir = pathlib.Path(__file__).parent

with open(top_dir / 'bb.v', "w") as f:
    f.write("""\
/**
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/** DO NOT EDIT -- This file is generated by `make_bb_v.py` file **/

""")
    for i in range(2, 64):
        f.write("""
/* {i}-bit wide adder */
(* blackbox *)
module add_b{i:02} (
        input [{i}:0] a,
        input [{i}:0] b,
        output [{i}:0] o);
endmodule
""".format(i=i))
